const productos = {
    TABLA: 'pedidos_productos',
    ID: 'ID',
    ID_PEDIDO: 'ID_PEDIDO',
    ID_TIENDA: 'ID_TIENDA',
    SLUG:'DES_SLUG_PRODUCTO',
    SKU: 'DES_SKU',
    NOMBRE: 'DES_NOMBRE_PRODUCTO',
    DESCRIPCION_CORTA: 'DES_DESCRIPCION_CORTA', 
    DESCRIPCION_LARGA: 'DES_DESCRIPCION_LARGA',
    DESCARGAR: 'DES_URL_DESCARGAR', 
    NUM_CANTIDAD: 'NUM_CANTIDAD',
    NUM_SUBTOTAL: 'NUM_SUBTOTAL',
    NUM_TOTAL: 'NUM_TOTAL',
    TIPO: 'NUM_TIPO_PRODUCTO',
    PRECIO_VENTA: 'NUM_PRECIO_VENTA',
    PRECIO_OFERTA: 'NUM_PRECIO_OFERTA', 
    COMISION: 'NUM_COMISION',
    ETIQUETAS: 'JSON_ETIQUETAS',
    IMPUESTOS: 'JSON_IMPUESTOS',
    CATEGORIAS: 'JSON_CATEGORIAS',
    FECHA: 'FECHA',
    ESTATUS: 'ESTATUS'

}

module.exports = productos