const productos = {
    TABLA: 'productos',
    ID: 'ID',
    ID_TIENDA: 'ID_TIENDA',
    SLUG:'DES_SLUG_PRODUCTO',
    SKU: 'DES_SKU',
    NOMBRE: 'DES_NOMBRE_PRODUCTO',
    DESCRIPCION_CORTA: 'DES_DESCRIPCION_CORTA', 
    DESCRIPCION_LARGA: 'DES_DESCRIPCION_LARGA',
    DESCARGAR: 'DES_URL_DESCARGAR', 
    IMAGEN: 'DES_URL_IMAGEN',
    TIPO: 'NUM_TIPO_PRODUCTO',
    PRECIO_VENTA: 'NUM_PRECIO_VENTA',
    PRECIO_OFERTA: 'NUM_PRECIO_OFERTA', 
    COMISION: 'NUM_COMISION',
    ETIQUETAS: 'JSON_ETIQUETAS',
    GALERIA: 'JSON_URL_GALERIA',
    INVENTARIO: 'BND_GESTIONAR_INVENTARIO',
    VENDER_INDIVIDUALMENTE: 'BND_VENDER_INDIVIDUALMENTE',
    FECHA: 'FECHA',
    ESTATUS: 'ESTATUS'

}

module.exports = productos