const reglas_descuento = {
    TABLA: 'reglas_descuento',
    ID: 'ID',
    DES_NOMBRE: 'DES_NOMBRE',
    DES_DESCRIPCION: 'DES_DESCRIPCION', 
    NUM_TIPO_REGLA: 'NUM_TIPO_REGLA',
    NUM_IMPORTE: 'NUM_IMPORTE', 
    FECHA_INICIO: 'FECHA_INICIO',
    FECHA_FIN: 'FECHA_FIN',
    BDN_ENVIO_GRATUITO: 'BDN_ENVIO_GRATUITO',
    NUM_GASTO_MINIMO: 'NUM_GASTO_MINIMO', 
    NUM_GASTO_MAXIMO: 'NUM_GASTO_MAXIMO',
    BND_USO_INDIVIDUAL: 'BND_USO_INDIVIDUAL',
    BND_EXCLUYE_ARTICULOS_OFERTA: 'BND_EXCLUYE_ARTICULOS_OFERTA',
    JSON_ID_PRODUCTOS_INCLUIDOS: 'JSON_ID_PRODUCTOS_INCLUIDOS',
    JSON_ID_CATEGORIAS_INCLUIDAS: 'JSON_ID_CATEGORIAS_INCLUIDAS',
    JSON_ID_USUARIOS_INCLUIDOS: 'JSON_ID_USUARIOS_INCLUIDOS',
    JSON_ROLES_INCLUIDOS: 'JSON_ROLES_INCLUIDOS',
    JSON_ID_TIENDAS_INCLUIDAS: 'JSON_ID_TIENDAS_INCLUIDAS',

    JSON_ID_PRODUCTOS_EXCLUIDOS: 'JSON_ID_PRODUCTOS_EXCLUIDOS',
    JSON_ID_CATEGORIAS_EXCLUIDAS: 'JSON_ID_CATEGORIAS_EXCLUIDAS',
    JSON_ID_TIENDAS_EXCLUIDAS: 'JSON_ID_TIENDAS_EXCLUIDAS',
    JSON_ID_USUARIOS_EXCLUIDOS: 'JSON_ID_USUARIOS_EXCLUIDOS',
    JSON_ROLES_EXCLUIDOS: 'JSON_ROLES_EXCLUIDOS',

    NUM_LIMITE_USO_POR_PROMO: 'NUM_LIMITE_USO_POR_PROMO',
    NUM_LIMITE_USO_POR_USUARIO: 'NUM_LIMITE_USO_POR_USUARIO',
    ID_USUARIO_ALTA: 'ID_USUARIO_ALTA',
    FECHA: 'FECHA',
    ESTATUS: 'ESTATUS'

}

module.exports = reglas_descuento