const suscripciones = {
    TABLA:  'suscripciones',
    ID:     'ID',
    ID_USUARIO: 'ID_USUARIO',
    ID_PRODUCTO: 'ID_PRODUCTO',
    ID_PEDIDO: 'ID_PEDIDO',
    NUM_TIPO_FRECUENCIA_PAGO: 'NUM_TIPO_FRECUENCIA_PAGO',
    NUM_FRECUENCIA_PAGO: 'NUM_FRECUENCIA_PAGO',
    JSON_NOTAS: 'JSON_NOTAS',
    FECHA_INICIO: 'FECHA_INICIO',
    FECHA_SIGUIENTE_PAGO: 'FECHA_SIGUIENTE_PAGO',
    FECHA_FIN: 'FECHA_SIGUIENTE_PAGO',
    ESTATUS: 'ESTATUS'
}

module.exports = suscripciones;